### PR TITLE
Use vmrun getGuestIPAddress to get IP (Big Sur)

### LINKED ISSUE #30: VMware Fusion can't find IP address on Big Sur
DHCP lease files are incorrect on Big Sur as networking now uses OS-provided facilities. One must use `vmrun` to get the correct guest IP.

See here for details: https://github.com/docker/machine/issues/4846

Fixed by https://github.com/docker/machine/pull/4847, which should apply here without much work.

Ironic that Fusion 12.1 now includes this at commit aaccce5 (which can't work), as listed in acknowledgements.pdf:

> `docker-machine-driver-vmware- aaccce554f6a23a80205520ade5b928d47ee9dec`

### PR DESCRIPTION
**Pull request by middagj**
This fixes #30, which is needed for Big Sur.

I copied it from docker/machine#4847, with two minor changes. First I put the vmrun before mac, as it isn't needed with the `vmrun getGuestIPAddress`. Secondly, I got rid of the capture group in the regex, as it is the same as the full full regex.

### CODE REVIEW

File: pkg/drivers/vmware/driver.go [hunk 1]
```diff
@@ -401,6 +406,18 @@ func (d *Driver) getMacAddressFromVmx() (string, error) {
 	return macaddr, nil
 }
 
+func (d *Driver) getIPfromVmrun() (string, error) {
+	vmx := d.vmxPath()
+
+	ip := regexp.MustCompile(`\d+\.\d+\.\d+\.\d+`)
+	stdout, _, _ := vmrun("getGuestIPAddress", vmx)
```
Comment (zarenner) [inline pkg/drivers/vmware/driver.go:413]: @middagj this doesn't seem to work for me, due to https://communities.vmware.com/t5/VMware-Fusion-Discussions/Using-vmrun-to-obtain-a-guests-IP-address-when-running-the-VM-in/td-p/2236978
It appears to be an issue with `getGuestIPAddress` not working correctly in VMWare headless mode.

Specifically, it fails with the very odd error `Error: The VMware Tools are not running in the virtual machine: <path_to_vmx>` eventually exhausting all retries, unless you open the VMs UI.

The fix (which is also bizarre) appears to be to add in a `-wait` as described in that issue. I've tested that with your changes and it then immediately gets the IP after the VM is started. I'm not sure how appropriate that is since there are other fallback methods to get the IP; perhaps it needs to be paired with a timeout of some sort.

```suggestion
	stdout, _, _ := vmrun("getGuestIPAddress", vmx, "-wait")
```

Comment (middagj) [reply pkg/drivers/vmware/driver.go]: I think I sometimes experienced this when I tried to get the docker-env variables in a shell. I added the suggestion along with a maximum wait. I put a default for 30s, should be enough I guess, and made it configurable. Not sure about the naming. Also not thoroughly tested. Does this solves the problem for you? Any suggestion on a proper default?

Very disappointing that the issue is open for almost 5 years now.

Comment (zarenner) [reply pkg/drivers/vmware/driver.go]: Yes, that appears to work just fine for me.

Tangentially related, unfortunately even with this change I now hit https://github.com/kubernetes/minikube/issues/3036 on VMWare since the new default "Internet Sharing" network mode conflicts with a dns proxy server on the host. It's unfortunate VMWare made such a breaking change here. The good news though is that VMWare does still appear to have a bridged networking mode (that still uses `bridge100` interface like sharing also seems to). That mode also seems to work fine with `vmrun getGuestIPAddress`, but it doesn't look like `docker-machine-driver-vmware` supports selecting the network mode on creation so I might have another PR coming this way...

**Review by zarenner — APPROVED** [review]

File: pkg/drivers/vmware/driver.go (hunk 1 above)
Comment (middagj) [reply pkg/drivers/vmware/driver.go]: I expect `-wait` to exit early, so better be on the safe side.

Isn't "Internet Sharing" always been the default with Fusion? I found it the most convenient with companies that usually have a VPN. That brings me to an additional problem I was facing after the upgrade to Big Sur. The network on the host wasn't fully accessible even with "Internet Sharing" on. I am using the solution of https://communities.vmware.com/t5/VMware-Fusion-Discussions/Share-host-VPN-with-guest/m-p/2810095/highlight/true#M170151

```zsh
#!/usr/bin/env zsh

# Source: https://communities.vmware.com/t5/VMware-Fusion-Discussions/Share-host-VPN-with-guest/m-p/2810095/highlight/true#M170151

set -e

if [[ -z $1 ]]; then
    echo >&2 "Specify interface"
    exit 1
fi
iface="$1"

if ! ifconfig | grep -qe "$iface"; then
    echo >&2 "Interface $iface does not exist"
    exit 1
fi

nat="$(sudo pfctl -a com.apple.internet-sharing/shared_v4 -s nat 2> /dev/null)"
if grep -qe "^nat on $iface inet from" <<< "$nat"; then
    echo >&2 "Interface $iface already added"
    exit
fi

src="$(sed -nE 's#^nat on en[0-9]+ inet from (.+) to any.*$#\1#p' <<< "$nat" | head -n1)"
if [[ -z $src ]]; then
    echo >&2 "Could not find source rule"
    exit 1
fi

nat="$nat"$'\n'"nat on $iface inet from $src to any -> ($iface) extfilter ei"
echo $nat
sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f - <<< "$nat" 2>/dev/null
```

It was apparently in the Release Notes, workaround is to connect on the machine which isn't really doable with minikube.

**Comment by smebberson** [comment]
Will this get merged in and released soon?

**Comment by smebberson** [comment]
@zarenner, is there anyway we can get this merged in and released?

**Comment by zarenner** [comment]
@smebberson I'm not a maintainer, just someone random who approved 😄. @frapposelli could you please take a look?

**Comment by mikeroySoft** [comment]
if @frapposelli wanted to make me a maintainer, I'd be more than happy to test and merge, and maintain things going forward...

**Comment by frapposelli** [comment]
done! thanks for your contribution @middagj !

@mikeroySoft happy to pass the baton to you Mike!

**Comment by mikeroySoft** [comment]
b88c1a83fc01dd42da0bef468396aa05
